### ISSUE TITLE
-* and *- block commenting

### ISSUE THREAD

**Issue by justJay-dev** [csharpfritz/oldTAML#19]
``` 
-*
This is a bunch of comment
block
things 
*-
```

**Comment by surlydev** [comment]
@justJay-dev where is -* and *- a block commenting syntax? I've never seen that before.

**Comment by csharpfritz** [comment]
Block commenting will not be supported as it betrays the TAML concept of each line is a record.

Multi-line comments can be achieved by prefixing each row with a `#` character

```
# This is
# a 
# multiline
# comment
# in TAML
```
