### ISSUE TITLE
Discussion:  Comment formatting

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/oldTAML#22]
Goal:  minimal notation required to start a comment

Do we need block comments?

Do we trigger 'comment mode' with \t-- or \t# ?

Some discussion was previously suggested in #19

**Comment by surlydev** [comment]
I propose that YES we do need block comments, they come in handy for quickly and easily excluding a block of code / tsql for example.

I also taking inspiration from Tsql, propose that we either use /* to start a block comment and */ to end it, or -- to start a line comment. Comment blocks and comment lines should be indentable. Anything after the start of a comment on a line is ignored.

Sure if you have an editor that has a Ctrl+K, Ctrl+C type of keyboard shortcut such as SSMS or VS, then the editor _could_ comment out each line with a --, however if the user is using another editor then /* and */ would be much easier.

```
root
    --my kvps start on the next line
                                                                                                     --This comment indented all the way over here
    key1 value1 -- this is my first kvp
    /* this block is ignored at the moment
                                                                                                     --This comment is also indented all the way over here
    key2 value2
    key3 value3
    */ --live data starts again here
    key4 value4
```

**Comment by hugodahl** [comment]
I do like @surlydev's suggestion of using the `/* .... */` as the block comment delimiters. This keeps it in line with JavaScript, even if JSON doesn't officially support comments. Same with single-line comments and the `//` prefix. It's also a very familiar practice for any C based or C-like language.

**Comment by BitCashCF** [comment]
I guess what it is, is that they ussually have a "METHOD Sign In "were every proptocol are tvalidated into nanogram.

**Comment by kyrvlasiuk** [comment]
```
## for line comments
#! to open block comment
!# to close
```
Pound(sharp) and exclamation are easy to reach as they are close to each other 
This what I would like comment to look like. I thing we will need to have a poll at some point.

**Comment by csharpfritz** [comment]
Resolved on Nov 15, 2020 stream:

ONLY Single-line comments supported in the spirit of CRLF / CR indicates a new record
Comments are indicated by first character `#`

Adding to specification 1.1
