### ISSUE TITLE
Discussion: Introduction of the Concept of Parser Directives

### ISSUE THREAD

**Issue by Stelzi79** [csharpfritz/oldTAML#25]
If(when) we introduce something like `Schema Definition`s we need a way to tell a possible parser, etc to tell what and where they can find the schema.

I suggest we introduce the concept of `Parser Directive`s.

In many usages like in programming languages look like some special comments. So I suggest the following syntax if(when) we provide a built in official specification of `Schema Definition`s:

```
	<CommentSequence><CommentSequence>TAML.Schema	<Place to find the Schema>
```

Alternatively if the `<CommentSequence>` turns out to be something not fitting in this case I suggest the following syntax:

```
	<CommentSequence>#TAML.Schema	<Place to find the Schema>
```

Notes:

- The `Parser Directive` is divided into a `<Namespace>` and a `<DirectiveName>` by a `.`
- The `Parser Directive` should be a resolvable package name in the environment the parser utilizes
- The `<Namespace>` token `TAML`is reserved for official specified `Parser Directive`s only
- Projects can define custom `Parser Directive`s that the official Parser can resolve through package manager and invoke there function
- If there are custom `Parser Directive`s there is a need for defining specification for how to interact with the resolvable package

The aspects of custom `Parser Directive`s being able to interact with the parser I would say would be a "down the line" feature that won't be in a 1.0 release version.

Additionally there would have to be the discussion about that we only allow `Parser Directive`s on top of the TAML file to make parsing the actual file not way more complicated or slow than it hast to be.

The goal of introducing the concept of `Parser Directive`s early in this project would be that there is an official syntax for such things already and nobody that needs such a feature is inventing there own syntax and make things looking messy.

**Comment by csharpfritz** [comment]
Resolved with specification 1.1:

Directives are defined on a line that starts with a `!` and have a name that is properly namespaced with an optional assigned value separated by one or more tabs

```
! TAML.EmptyArraySupported  FALSE
```
