### ISSUE TITLE
Add some concrete examples of possible TAML usage

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/oldTAML#44]
Demonstrate a hypothetical use of TAML by converting the following to TAML documents with appropriate documentation accompanying:

- [x] package.json
- [x] appsettings.json
- [x] Kubernetes YML doc?  
- [x] GitHub workflow YML?

**Comment by londospark** [comment]
I've just tried to do something with a GitHub Workflow YAML file and came across an issue that I have written up in https://github.com/csharpfritz/TAML/issues/26#issuecomment-695839056

**Comment by londospark** [comment]
I have a simple `appsettings.taml` here:

```
Logging
	LogLevel
		Default				Information
		Microsoft			Warning
		Microsoft.Hosting.Lifetime	Information

AllowedHosts	*
```

The JSON original would be:

```javascript
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "AllowedHosts": "*"
}
```

**Comment by londospark** [comment]
Where would it be best for these files to be located and in the instances where a 1:1 mapping is undesirable/not yet possible would it be worth us still having an example and just noting that you would need a specific converter to make it work (until we get schemas done at least)

**Comment by CodeItQuick** [comment]
As can be seen above, I proposed a spot for those files to live and started a PR on a separate branch for the files. Cfritz was broadcasting and pushing to the repo at the time so its out of sync with master, I'll wait until the end of the stream to fix.

**Comment by csharpfritz** [comment]
Added Kubernetes and GitHub actions sample docs in the concrete_samples folder
