### ISSUE TITLE
Issue:  How to define a key value pair with an empty value

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/oldTAML#61]
In JSON, a key value pair with an empty text value appears like the following:

```
"key": ""
```

**Comment by Stelzi79** [comment]
I would argue this the same as I did in #60 because at the root they are the same issue about an optional setting in a configuration file.

**Comment by csharpfritz** [comment]
Resolved for specification 1.1:
Empty value is indicated with a value in the format `!""`

The magic characters `!""` indicate the empty value
