### ISSUE TITLE
Need Configuration package for .NET 5+

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/oldTAML#63]
Let's build `Microsoft.Extensions.Configuration.TAML` but it needs to be in our own namespace

**Comment by csharpfritz** [comment]
Perhaps the package name should be `TAML.Microsoft.Extensions.Configuration`

**Comment by TGrannen** [comment]
@csharpfritz I caught you talking about this on stream and thought I'd give it a go (even though you mentioned it not being on the horizon yet). But I was curious about how the new C# projects should be structured. By attempting to follow the naming conventions, I've started with adding a new class library and test projects shown below. 

```
  /dotnet
    /Configuration.Taml.NET         <-- New
    /Taml.NET
    /Test.Configuration.Taml.NET    <-- New
    /Test.Taml.NET 
```

I'm leaning towards putting them in sub-folder `Configuration` to better denote the separation of responsibilities, but I didn't know if there was a particular convention or preference that should be used for the project naming and structure.

**Comment by csharpfritz** [comment]
@TGrannen Thank you for your interest in helping!

I think you're right - we need a little organization on this.  Perhaps we should rebrand the `/parsers` folder to `/src` and maintain the `dotnet` and `python` folders.  We can then create language specific folders named for the package they will deliver to that ecosystem.  For the .NET ecosystem and the 2 NuGet packages we seek to deliver:

```
/src/dotnet
   /Taml.NET
      /Taml.NET
      /Test.Taml.NET
   /Configuration.Taml.NET
      /Configuraiton.Taml.NET
      /Test.Configuration.Taml.NET
```

Thoughts?

**Comment by TGrannen** [comment]
@csharpfritz Makes sense to me! I can get the folder changes up in a PR to review first, and then I'll integrate that the configuration changes as well.
