### ISSUE TITLE
Dotnet implementation doesn't properly handle Complex Child Document Test Case

### ISSUE THREAD

**Issue by TGrannen** [csharpfritz/oldTAML#68]
During the investigation of #63, I've found that the dotnet parser implementation does not properly parse the `Complex Child Document` test case within the Test project.  The issue here is that `key3` under the `root` does not have any children underneath it when it should have `item1`, `item2`, `etc...`. The other keys (`key1` &`key2`) also do not have their corresponding values.

The test TAML file and screenshot from Visual Studio are shown below.

### ComplexChildDocument.taml
```
root
	key1		value1
	key2		value2
	key3
		item1
		item2
		item3
		item4
			key41			value41
			key42			value42
			key43			value43
			key44			value44
```
### Visual Studio Debugger
![image](https://user-images.githubusercontent.com/2957152/99206516-993f5700-2789-11eb-97fa-5013afaf994f.png)

**Comment by csharpfritz** [comment]
Thank you for this fix!
